version: '3'

services:
  angular-service:
    image: angular_app
    ports:
      - "30002:80"
    networks:
      - my-network

  springboot-service:
    image: springboot_app
    ports:
      - "30001:8080"
    networks:
      - my-network

  sonarqube:
    image: sonarqube:latest
    ports:
      - "9000:9000"
    networks:
      - my-network
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonarqube-db:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar

  sonarqube-db:
    image: postgres:latest
    networks:
      - my-network
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar

  nexus:
    image: sonatype/nexus3:latest
    ports:
      - "8081:8081"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
