apiVersion: apps/v1
kind: Deployment
metadata:
  name: springbootservicedeployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springbootservice
  template:
    metadata:
      name: springbootservice
      labels:
        app: springbootservice
    spec:
      containers:
      - name: springbootservicecontainer
        image: springboot_app
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: springbootservicesvc
spec:
  type: NodePort
  selector:
    app: springbootservice
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30001
