apiVersion: apps/v1
kind: Deployment
metadata:
  name: angularservicedeployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: angularservice
  template:
    metadata:
      name: angularservice
      labels:
        app: angularservice
    spec:
      containers:
      - name: angularservicecontainer
        image: angular_app
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: angularservicesvc
spec:
  type: NodePort
  selector:
    app: angularservice
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30002
